#!/usr/bin/env node
/**
 * Compile postMessage v2 JSON Schemas into freestanding JS
 * validators using Ajv standalone mode. Output lives at
 * `src/generated/postmessage-v2/` and is committed-but-derived: regenerate on
 * any schema edit and commit the resulting JS so CI does not need Ajv at test
 * time.
 *
 */
import Ajv from "ajv/dist/2020.js"
import standaloneCode from "ajv/dist/standalone/index.js"
import addFormats from "ajv-formats"
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const SCHEMA_DIR = join(__dirname, "../schemas/postmessage-v2")
const OUT_DIR = join(__dirname, "../src/generated/postmessage-v2")

mkdirSync(OUT_DIR, { recursive: true })

const ajv = new Ajv({
  code: { source: true, esm: true },
  strict: false,
  allErrors: true,
})
addFormats(ajv)

const all = []
function walk(d) {
  for (const f of readdirSync(d)) {
    const p = join(d, f)
    if (statSync(p).isDirectory()) walk(p)
    else if (p.endsWith(".json")) all.push(p)
  }
}
walk(SCHEMA_DIR)

for (const p of all) {
  const schema = JSON.parse(readFileSync(p, "utf-8"))
  ajv.addSchema(schema)
}

const DTS_BODY =
  "// Auto-generated by scripts/compile-schemas.mjs.\n" +
  "// Types the Ajv standalone-compiled validator function so postmessage_v2.ts\n" +
  "// can consume it without `@ts-expect-error` suppressions.\n" +
  "interface ValidatorFn {\n" +
  "  (data: unknown): boolean\n" +
  "  errors?: Array<Record<string, unknown>> | null\n" +
  "}\n" +
  "declare const validate: ValidatorFn\n" +
  "export default validate\n" +
  "export { validate }\n"

let written = 0
for (const p of all) {
  const schema = JSON.parse(readFileSync(p, "utf-8"))
  const validate = ajv.getSchema(schema.$id)
  if (!validate) throw new Error(`Could not retrieve compiled validator for ${schema.$id}`)
  const moduleCode = standaloneCode(ajv, validate)
  const rel = relative(SCHEMA_DIR, p).replace(/\.json$/, ".js")
  const outPath = join(OUT_DIR, rel)
  const dtsPath = outPath.replace(/\.js$/, ".d.ts")
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, moduleCode)
  writeFileSync(dtsPath, DTS_BODY)
  written++
}

console.log(`Compiled ${written} postMessage v2 schema(s) (+ .d.ts) to ${relative(process.cwd(), OUT_DIR)}`)
