// postMessage v2 validator helper.
//
// Wraps Ajv standalone-compiled validators. The compiled .js modules live at
// src/generated/postmessage-v2/ and are committed-but-derived: run
// `yarn build:schemas` to regenerate after editing a schema. Each .js file
// ships an auto-generated .d.ts sibling so this module's imports type-check
// without `@ts-expect-error` suppressions.
//

import envelopeValidator from "./generated/postmessage-v2/envelope.js"
import readyValidator from "./generated/postmessage-v2/ready.js"
import resizeValidator from "./generated/postmessage-v2/resize.js"
import cancelValidator from "./generated/postmessage-v2/cancel.js"
import consentStateValidator from "./generated/postmessage-v2/consent/state.js"
import consentCompleteValidator from "./generated/postmessage-v2/consent/complete.js"
import consentErrorValidator from "./generated/postmessage-v2/consent/error.js"
import consentDeadlineValidator from "./generated/postmessage-v2/consent/deadline.js"
import approvalStateValidator from "./generated/postmessage-v2/approval/state.js"
import approvalCompleteValidator from "./generated/postmessage-v2/approval/complete.js"
import approvalErrorValidator from "./generated/postmessage-v2/approval/error.js"
import approvalDeadlineValidator from "./generated/postmessage-v2/approval/deadline.js"
// signing kind. Validators generated by `yarn build:schemas` from the
// authored schemas/postmessage-v2/signature/*.json (committed-but-derived).
import signatureStateValidator from "./generated/postmessage-v2/signature/state.js"
import signatureCompleteValidator from "./generated/postmessage-v2/signature/complete.js"
import signatureErrorValidator from "./generated/postmessage-v2/signature/error.js"
import signatureDeadlineValidator from "./generated/postmessage-v2/signature/deadline.js"

import { MESSAGE_TYPES_V2 } from "./constants"

export type DecisionKind = "consent" | "approval" | "signature_request"

export interface Envelope {
  type: string
  kind: DecisionKind
  version: 2
  payload: Record<string, unknown>
  ts: string
  message_id: string
}

export interface ValidationError {
  instancePath?: string
  schemaPath?: string
  keyword?: string
  message?: string
  params?: Record<string, unknown>
}

export interface ValidationResult {
  valid: boolean
  errors: ValidationError[] | null
}

interface ValidatorFn {
  (data: unknown): boolean
  errors?: ValidationError[] | null
}

const VALIDATORS: Record<string, Record<string, ValidatorFn>> = {
  [MESSAGE_TYPES_V2.READY]: { _agnostic: readyValidator as ValidatorFn },
  [MESSAGE_TYPES_V2.RESIZE]: { _agnostic: resizeValidator as ValidatorFn },
  [MESSAGE_TYPES_V2.CANCEL]: { _agnostic: cancelValidator as ValidatorFn },
  [MESSAGE_TYPES_V2.STATE]: {
    consent: consentStateValidator as ValidatorFn,
    approval: approvalStateValidator as ValidatorFn,
    signature_request: signatureStateValidator as ValidatorFn,
  },
  [MESSAGE_TYPES_V2.COMPLETE]: {
    consent: consentCompleteValidator as ValidatorFn,
    approval: approvalCompleteValidator as ValidatorFn,
    signature_request: signatureCompleteValidator as ValidatorFn,
  },
  [MESSAGE_TYPES_V2.ERROR]: {
    consent: consentErrorValidator as ValidatorFn,
    approval: approvalErrorValidator as ValidatorFn,
    signature_request: signatureErrorValidator as ValidatorFn,
  },
  [MESSAGE_TYPES_V2.DEADLINE]: {
    consent: consentDeadlineValidator as ValidatorFn,
    approval: approvalDeadlineValidator as ValidatorFn,
    signature_request: signatureDeadlineValidator as ValidatorFn,
  },
}

const envelopeFn = envelopeValidator as ValidatorFn

/**
 * Validate just the top-level envelope (type, kind, version, payload, ts, message_id).
 * Per-payload validation requires {@link validatePayload}.
 */
export function validateEnvelope(message: unknown): ValidationResult {
  const valid = envelopeFn(message)
  return { valid, errors: valid ? null : (envelopeFn.errors ?? null) }
}

/**
 * Validate just the payload of an already-envelope-valid message.
 * Routes by `message.type` and (for kind-specific types) `message.kind`.
 */
export function validatePayload(message: Envelope): ValidationResult {
  const typeMap = VALIDATORS[message.type]
  if (!typeMap) {
    return { valid: false, errors: [{ message: `Unknown type ${message.type}` }] }
  }
  const validator = typeMap._agnostic ?? typeMap[message.kind]
  if (!validator) {
    return {
      valid: false,
      errors: [{ message: `No validator for ${message.type}/${message.kind}` }],
    }
  }
  const valid = validator(message.payload)
  return { valid, errors: valid ? null : (validator.errors ?? null) }
}

/**
 * Validate envelope first, then payload. Short-circuits on envelope failure.
 */
export function validate(message: unknown): ValidationResult {
  const envelopeResult = validateEnvelope(message)
  if (!envelopeResult.valid) return envelopeResult
  return validatePayload(message as Envelope)
}
